import fs from "node:fs";

import { constants } from "#pkg/constants.js";

export function getRules() {
  /* the rules file is generated by this package itself, so its shape is known */
  // oxlint-disable-next-line typescript/no-unsafe-type-assertion
  return JSON.parse(fs.readFileSync(constants.RULES_PATH, { encoding: "utf8" })) as string[];
}
